WIP begin work on rgb.to_hsl() impl
vaidehijoshi/css-colors pull request #6
Opened 2018-10-08 01:03 UTC by vaidehijoshi

Try to get luminosity (l) of HSL working

2018-10-12 00:05 UTC, vaidehijoshi commented
i rebased a commit into this PR that splits up Angles into it's own module, so am changing the base branch to make diffs more obvious

2018-10-12 00:54 UTC, vaidehijoshi commented
@chancancode i think this is ok to merge, and then i can refactor how i handle the saturation & luminosity once i have impl'd percentages. let me know if you disagree, though.

2018-10-12 01:01 UTC, chancancode requested changes

2018-10-12 01:01 UTC, chancancode commented on src/lib.rs
> +    }
I think this whole method can just be `self.to_rgb().to_hsl()`

2018-10-12 01:01 UTC, chancancode commented on src/lib.rs
>          // FIXME: update these tests once HSL <-> RBG impl exists
Pending

2018-10-12 18:23 UTC, vaidehijoshi commented on src/lib.rs
>          // FIXME: update these tests once HSL <-> RBG impl exists
do you mean impl the hsl --> rgb in this pr itself?

2018-10-13 01:06 UTC, chancancode commented on src/lib.rs
>          // FIXME: update these tests once HSL <-> RBG impl exists
ah nvm I thought it was already working and you just forgot to remove this

2018-10-15 00:45 UTC, vaidehijoshi commented on src/lib.rs
>          // FIXME: update these tests once HSL <-> RBG impl exists
ok, cool :) going to do hsl --> rgb next!

2018-10-15 00:51 UTC, merged